name: "Verged3d Addon"
description: "Sends Home Assistant states to verge3d api server"
version: "0.0.16"
slug: "verged3d-addon"
homeassistant_api: true
supervisor_api: true
#hassio_role: homeassistant
host_network: true
full_access: true
privileged:
  - SYS_ADMIN
apparmor: false
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  9765/tcp: 9765
ports_description:
  9765/tcp: WebSocket 서버 포트  
options:
  polling_interval: 10 
  timeout: 30
schema:
  polling_interval: int(10,3600)
  timeout: int(5,300)